# Generated by Django 4.2.2 on 2023-06-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_api', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
