# Generated by Django 4.2.2 on 2023-06-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_api', '0004_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
